name: FrugalAdaptiveComputation
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - argh=0.26.2=pyh9f0ad1d_1002
  - blas=2.111=mkl
  - blas-devel=3.9.0=11_win64_mkl
  - brotlipy=0.7.0=py38h294d835_1001
  - ca-certificates=2021.5.30=h5b45459_0
  - certifi=2021.5.30=py38haa244fe_0
  - cffi=1.14.6=py38hd8c33c5_0
  - chardet=4.0.0=py38haa244fe_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=8.0.1=py38haa244fe_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - configparser=5.0.2=pyhd8ed1ab_0
  - cryptography=3.4.7=py38hd7da0ea_0
  - cudatoolkit=11.1.1=heb2d755_7
  - docker-pycreds=0.4.0=py_0
  - freetype=2.10.4=h546665d_1
  - gitdb=4.0.7=pyhd8ed1ab_0
  - gitpython=3.1.18=pyhd8ed1ab_0
  - gql=0.1.0=py_0
  - graphql-core=3.1.6=pyhd8ed1ab_0
  - idna=3.1=pyhd3deb0d_0
  - intel-openmp=2021.3.0=h57928b3_3372
  - jpeg=9b=hb83a4c4_2
  - libblas=3.9.0=11_win64_mkl
  - libcblas=3.9.0=11_win64_mkl
  - liblapack=3.9.0=11_win64_mkl
  - liblapacke=3.9.0=11_win64_mkl
  - libpng=1.6.37=h1d00b33_2
  - libprotobuf=3.17.2=h7755175_1
  - libtiff=4.2.0=hd0e1b90_0
  - libuv=1.42.0=h8ffe710_0
  - lz4-c=1.9.3=h8ffe710_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mkl=2021.3.0=hb70f87d_564
  - mkl-devel=2021.3.0=h57928b3_565
  - mkl-include=2021.3.0=hb70f87d_564
  - msys2-conda-epoch=20160418=1
  - ninja=1.10.2=h5362a0b_0
  - numpy=1.21.2=py38h089cfbf_0
  - nvidia-ml=7.352.0=py_0
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1k=h8ffe710_1
  - pathtools=0.1.2=py_1
  - pillow=8.3.1=py38h4fa10fc_0
  - pip=21.2.4=pyhd8ed1ab_0
  - promise=2.3=py38haa244fe_3
  - protobuf=3.17.2=py38h885f38d_0
  - psutil=5.8.0=py38h294d835_1
  - pycparser=2.20=pyh9f0ad1d_2
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py38haa244fe_3
  - python=3.8.0=hc9e8b01_5
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.9.0=py3.8_cuda11.1_cudnn8_0
  - pyyaml=5.4.1=py38h294d835_1
  - requests=2.26.0=pyhd8ed1ab_0
  - sentry-sdk=1.3.1=pyhd8ed1ab_0
  - setuptools=57.4.0=py38haa244fe_0
  - shortuuid=1.0.1=py38haa244fe_4
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - sqlite=3.36.0=h8ffe710_0
  - subprocess32=3.5.4=py_1
  - tbb=2021.3.0=h2d74725_0
  - tk=8.6.11=h8ffe710_0
  - torchaudio=0.9.0=py38
  - torchvision=0.10.0=py38_cu111
  - typing_extensions=3.10.0.0=pyha770c72_0
  - ucrt=10.0.20348.0=h57928b3_0
  - urllib3=1.26.6=pyhd8ed1ab_0
  - vc=14.2=hb210afc_5
  - vs2015_runtime=14.29.30037=h902a5da_5
  - wandb=0.11.2=pyhd8ed1ab_0
  - watchdog=0.10.4=py38haa244fe_0
  - wheel=0.37.0=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=py38haa244fe_2
  - xz=5.2.5=h62dcd97_1
  - yaml=0.2.5=he774522_0
  - zlib=1.2.11=h62dcd97_1010
  - zstd=1.4.9=h6255e5f_0
  - pip:
    - tqdm==4.62.2
prefix: C:\Users\Sam\anaconda3\envs\FrugalAdaptiveComputation
