wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.2
    code_path: code/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.0
    t:
      1:
      - 1
      4: 3.8.0
      5: 0.11.2
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 128
budget:
  desc: null
  value: 5
hidden_dims:
  desc: null
  value:
  - 128
input_size:
  desc: null
  value: 64
lr:
  desc: null
  value: 1E-4
n_samples_parity:
  desc: null
  value: 100000
