lr:
  desc: Learning rate
  value: 1E-4
n_epoch:
  value: 100
batch_size:
  desc: Batch size
  value: 128
input_size:
  desc: Input size to model / task dependent
  value: 64
n_memory:
  desc: Memory dimensions
  value: 10
budget:
  desc: Max number of iters allowed
  value: 5
n_samples_parity:
  desc: Number of samples in dataset
  value: 100000
hidden_dims:
  desc: Hidden dims of recurrent unit
  value: [128]