lr:
  desc: Learning rate
  value: 3.0E-4
n_epoch:
  value: 10000
batch_size:
  desc: Batch size
  value: 128
n_memory:
  desc: Memory dimensions
  value: 10
budget:
  desc: Max number of iters allowed
  value: 5
batches_per_epoch:
  value: 100
hidden_dims:
  desc: Hidden dims of recurrent unit
  value: [128]
n_elems:
  desc: Number of elements in parity vector
  value: 8 
n_hidden:
  desc: n_hidden dimensions of cell
  value: 128